{
    "name": "gestion_bibliotheque",
    "version": "1.0",
    "category": "bibliotheque",
    "author": "OUAFI Mohammed Zakaria",
    "depends": ["project"],
    "description": "Ce module est destiné à la gestion des bibliotheque",
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/auteur.xml",
        "views/livre.xml",
        "views/emprunteur.xml",
        "views/emprunt.xml",
        "wizard/emprunt_wizard.xml",
        "report/emprunteur_report.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
